name: "Rust Cache"
description: "A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults."
author: "Arpad Borsos <swatinem@swatinem.de>"
inputs:
  workspaces:
    description: "Paths to multiple Cargo workspaces and their target directories, separated by newlines."
    required: false
runs:
  using: "node20"
  main: "dist/trim/index.js"
  post-if: "true"
branding:
  icon: "archive"
  color: "gray-dark"
